# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '阅读' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FMDB', '~> 2.6.2'
  pod 'MJExtension', '~> 3.0.11'
  pod 'Masonry', '~> 1.0.2'
  pod 'ZipArchive', '~> 1.4.0'
  pod 'DTCoreText'
  pod 'MWPhotoBrowser'
  pod 'MJRefresh'
  # Pods for 阅读

end
